# Generated by Django 4.0.4 on 2022-06-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_moderator'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='https://www.gravatar.com/avatar/bf5c77ba8067db6121b6f02d87674dcd?d=https%3A%2F%2Fexample.com%2Fstatic%2Fimages%2Fdefaultavatar.jpg&s=40 40 40', upload_to=''),
        ),
    ]
