# Generated by Django 4.0.4 on 2022-06-01 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_moderator',
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='https://www.gravatar.com/avatar/bf5c77ba8067db6121b6f02d87674dcd?d=https%3A%2F%2Fexample.com%2Fstatic%2Fimages%2Fdefaultavatar.jpg&s=404040', upload_to=''),
        ),
    ]
