# Generated by Django 4.0.4 on 2022-06-01 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0003_alter_board_uid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField(max_length=1000)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='boards.board')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='thread_uid', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
