# Generated by Django 4.0.4 on 2022-06-01 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('moderator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='moderator', to=settings.AUTH_USER_MODEL)),
                ('uid', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='uid', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
