# Generated by Django 4.0.4 on 2022-06-01 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0002_alter_board_moderator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='uid', to=settings.AUTH_USER_MODEL),
        ),
    ]
